plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom-remap'
}
dependencies {
    runtimeOnly("org.javassist:javassist:3.30.2-GA")
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings loom.officialMojangMappings()
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
    modImplementation("com.zigythebird.playeranim:PlayerAnimationLibFabric:${pal_version}") {
        transitive = false
    }
    implementation("com.zigythebird.playeranim:PlayerAnimationLibCore:${pal_version}") {
        transitive = false
    }
    implementation("com.zigythebird:mochafloats:4.1.5") {
        transitive = false
    }
    modImplementation("maven.modrinth:bendable-cuboids:${bendable_cuboids_fabric_version}") {
        transitive = false
    }
    include("maven.modrinth:bendable-cuboids:${bendable_cuboids_fabric_version}") {
        transitive = false
    }
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${mixinsquared_version}")))
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('../run/fabric-client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('../run/fabric-server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.findByName(variant)?.with {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
